<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
        'key' => 'group_6605804bd3539',
        'title' => 'Order Data',
        'fields' => array(
            array(
                'key' => 'field_6605820eabcff',
                'label' => 'ServiceID',
                'name' => 'service_id',
                'aria-label' => '',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'social-service',
                ),
                'post_status' => '',
                'taxonomy' => '',
                'filters' => '',
                'return_format' => 'id',
                'acfe_add_post' => 0,
                'acfe_edit_post' => 0,
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'min' => '',
                'max' => '',
                'elements' => '',
                'acfe_field_group_condition' => 0,
                'bidirectional' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'serviceid',
                'graphql_connection_type' => 'one_to_many',
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_6605804dabcfc',
                'label' => 'Service Name',
                'name' => 'service_name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'service',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_660581b8abcfd',
                'label' => 'Plan',
                'name' => 'plan',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'required_message' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'plan',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_660581d7abcfe',
                'label' => 'Plan Count',
                'name' => 'count',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'graphql_field_name' => '',
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_66058288abd01',
                'label' => 'Plan Amount',
                'name' => 'plan_amount',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'planAmount',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_6605827cabd00',
                'label' => 'Plan Discount',
                'name' => 'plan_discount',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'planDiscount',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_66058295abd02',
                'label' => 'Total Amount',
                'name' => 'total_amount',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'totalAmount',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_660582dfabd03',
                'label' => 'Payment Method',
                'name' => 'payment_method',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'required_message' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'paymentMethod',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_660582f1abd04',
                'label' => 'Payment ID',
                'name' => 'payment_id',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'paymentId',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_660583331277c',
                'label' => 'Account ID',
                'name' => 'account_id',
                'aria-label' => '',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'social-media-account',
                ),
                'post_status' => '',
                'taxonomy' => '',
                'filters' => '',
                'return_format' => 'id',
                'acfe_add_post' => 0,
                'acfe_edit_post' => 0,
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'min' => '',
                'max' => '',
                'elements' => '',
                'acfe_field_group_condition' => 0,
                'bidirectional' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'accountId',
                'graphql_connection_type' => 'one_to_many',
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_660583491277d',
                'label' => 'User ID',
                'name' => 'user_id',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'userId',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_6605a21d21144',
                'label' => 'Service Posts',
                'name' => 'service_posts',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Row',
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'servicePost',
                'graphql_non_null' => 0,
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6605a2b421145',
                        'label' => 'Post Title|Link',
                        'name' => 'post',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'show_in_graphql' => 1,
                        'graphql_description' => '',
                        'graphql_field_name' => 'postTitlelink',
                        'graphql_non_null' => 0,
                        'parent_repeater' => 'field_6605a21d21144',
                    ),
                ),
                'acfe_repeater_stylised_button' => 0,
            ),
            array(
                'key' => 'field_6605a9aa4412d',
                'label' => 'Status',
                'name' => 'status',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'graphql_field_name' => 'status',
                'choices' => array(
                    'PENDING' => 'PENDING',
                    'PAID' => 'PAID',
                    'FAILED' => 'FAILED',
                    'PROCESSING' => 'PROCESSING',
                    'COMPLETED' => 'COMPLETED',
                    'CANCELLED' => 'CANCELLED',
                ),
                'default_value' => 'PENDING',
                'return_format' => 'value',
                'multiple' => 0,
                'max' => '',
                'prepend' => '',
                'append' => '',
                'allow_null' => 0,
                'ui' => 0,
                'acfe_field_group_condition' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_non_null' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
                'min' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service-order',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'orderData',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
        'acfe_display_title' => '',
        'acfe_meta' => '',
        'acfe_note' => '',
    ));
});

